/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BlacklistRouteImport } from './routes/blacklist'
import { Route as EntriesRouteImport } from './routes/entries'
import { Route as FriendLinksRouteImport } from './routes/friend-links'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TaxonomyRouteImport } from './routes/taxonomy'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BlacklistRoute = BlacklistRouteImport.update({
  id: '/blacklist',
  path: '/blacklist',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesRoute = EntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendLinksRoute = FriendLinksRouteImport.update({
  id: '/friend-links',
  path: '/friend-links',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxonomyRoute = TaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/audit': typeof AuditRoute
  '/blacklist': typeof BlacklistRoute
  '/entries': typeof EntriesRoute
  '/friend-links': typeof FriendLinksRoute
  '/promotions': typeof PromotionsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/taxonomy': typeof TaxonomyRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/audit': typeof AuditRoute
  '/blacklist': typeof BlacklistRoute
  '/entries': typeof EntriesRoute
  '/friend-links': typeof FriendLinksRoute
  '/promotions': typeof PromotionsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/taxonomy': typeof TaxonomyRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/audit': typeof AuditRoute
  '/blacklist': typeof BlacklistRoute
  '/entries': typeof EntriesRoute
  '/friend-links': typeof FriendLinksRoute
  '/promotions': typeof PromotionsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/taxonomy': typeof TaxonomyRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/audit'
    | '/blacklist'
    | '/entries'
    | '/friend-links'
    | '/promotions'
    | '/review'
    | '/settings'
    | '/taxonomy'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/audit'
    | '/blacklist'
    | '/entries'
    | '/friend-links'
    | '/promotions'
    | '/review'
    | '/settings'
    | '/taxonomy'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/audit'
    | '/blacklist'
    | '/entries'
    | '/friend-links'
    | '/promotions'
    | '/review'
    | '/settings'
    | '/taxonomy'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AuditRoute: typeof AuditRoute
  BlacklistRoute: typeof BlacklistRoute
  EntriesRoute: typeof EntriesRoute
  FriendLinksRoute: typeof FriendLinksRoute
  PromotionsRoute: typeof PromotionsRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  TaxonomyRoute: typeof TaxonomyRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blacklist': {
      id: '/blacklist'
      path: '/blacklist'
      fullPath: '/blacklist'
      preLoaderRoute: typeof BlacklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries': {
      id: '/entries'
      path: '/entries'
      fullPath: '/entries'
      preLoaderRoute: typeof EntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friend-links': {
      id: '/friend-links'
      path: '/friend-links'
      fullPath: '/friend-links'
      preLoaderRoute: typeof FriendLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxonomy': {
      id: '/taxonomy'
      path: '/taxonomy'
      fullPath: '/taxonomy'
      preLoaderRoute: typeof TaxonomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AuditRoute: AuditRoute,
  BlacklistRoute: BlacklistRoute,
  EntriesRoute: EntriesRoute,
  FriendLinksRoute: FriendLinksRoute,
  PromotionsRoute: PromotionsRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  TaxonomyRoute: TaxonomyRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
