// Writes the categories + tags from @tgbox/shared as an insert-only D1 migration.
// D1 is the source of truth for taxonomy: admins rename, reorder and re-icon categories in the admin
// app, so this only adds rows that don't exist yet and never overwrites existing names or order.
// New seed rows: `pnpm --filter @tgbox/db exec drizzle-kit generate --custom --name taxonomy_<n>`,
// then `node scripts/gen-taxonomy-migration.ts --out packages/db/migrations/<that file>.sql`.
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { parseArgs } from "node:util";
import { categories, tags } from "../packages/shared/src/index.ts";
import { repoRoot } from "./lib/run.ts";
import { sqlValue } from "./lib/sql.ts";

export function taxonomySql() {
  const lines = [
    "-- Generated by scripts/gen-taxonomy-migration.ts from @tgbox/shared. Do not edit by hand.",
    "-- Insert-only: D1 is the source of truth (edited in the admin); existing rows are left untouched.",
  ];
  for (const c of categories) {
    lines.push(
      `INSERT INTO categories (slug, kind, name_zh, name_en, sort) VALUES (${[c.slug, c.kind, c.nameZh, c.nameEn, c.sort].map(sqlValue).join(", ")}) ` +
        "ON CONFLICT (kind, slug) DO NOTHING;",
    );
  }
  for (const t of tags) {
    lines.push(
      `INSERT INTO tags (slug, name_zh, name_en) VALUES (${[t.slug, t.nameZh, t.nameEn].map(sqlValue).join(", ")}) ` +
        "ON CONFLICT (slug) DO NOTHING;",
    );
  }
  return `${lines.join("\n")}\n`;
}

if (import.meta.main) {
  const { values } = parseArgs({
    options: { out: { type: "string" } },
  });
  // No default: overwriting an applied migration (e.g. 0002_taxonomy.sql) would be silently ignored.
  if (!values.out)
    throw new Error("usage: node scripts/gen-taxonomy-migration.ts --out <new migration>.sql");
  const out = path.resolve(repoRoot, values.out);
  await writeFile(out, taxonomySql());
  console.log(
    `wrote ${categories.length} categories + ${tags.length} tags → ${path.relative(repoRoot, out)}`,
  );
}
